services:
  neo4j:
    image: neo4j:5.10-community
    container_name: crime_network_db
    ports:
      - "7474:7474" # HTTP Browser
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: